### ISSUE TITLE
Insert request made using service_role key still unable to bypass RLS

### ISSUE THREAD

**Issue by akarshghale** [supabase/supabase-py#1001]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

So, I am making an insert request in my table, the issue is on my local machine with supabase 2.6.0 is it working fine as intended i.e. insert records as service_role that should bypass RLS but on staging I have supabase 2.10.0 and it is inserting the records as role authenticated with user_id i mentioned in the user_id column of the table even though I have no login code and also the key is service_role key leading to RLS error.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Create a table with RLS
Enable RLS
**Insert a record in the table with column user_id of an actual user**

## Expected behavior

The records should have been inserted as service_role without triggering RLS policy.

## Screenshots

From the logs, 
 ```
"authorization": [
            {
              "invalid": null,
              "payload": [
                {
                  "algorithm": "HS256",
                  "issuer": "https://xxxxxxxxxxxxus.supabase.co/auth/v1", (hidden for security reasons)
                  "key_id": "gnKsQ+2zzxM9F1RT",
                  "role": "authenticated",
                  "signature_prefix": "qnJVPy",
                  "subject": "<UUID user_id of the column user_id is being shown here which I removed>"
```

Part of the code I used and also you can make out the DB schema.

  ```
data_dict = {
        "user_id": user_id,
        "organization_id": organization_id,
        "source": source,
        "review": review,
        "author": author,
        "author_email": author_email,
        "company_name": company_name,
        "timestamp": timestamp,
        "rating": rating,
        "tags": tags,
        "status": "unprocessed"
    }

    # Store the data in the 'unprocessed_reviews' table
    result, error = supabase.table('unprocessed_reviews').insert([data_dict]).execute()
    if error[1] is not None:
        raise HTTPException(status_code=500, detail="Error storing data")
    
    return {"message": "Data stored successfully", "success": True}
```

Code error:
```

    result, error = supabase.table('unprocessed_reviews').insert([data_dict]).execute()
  File "/usr/local/lib/python3.10/site-packages/postgrest/_sync/request_builder.py", line 78, in execute
    raise APIError(r.json())
postgrest.exceptions.APIError: {'code': '42501', 'details': None, 'hint': None, 'message': 'new row violates row-level security policy for table "unprocessed_reviews"'}

```

## System information

- OS: MacOS latest
- Browser (if applies) NA
- Version of supabase-py: 2.10.0
- Version of Node.js: NA

## Additional context

The problem is the requests are being executed as **authenticated** as the **user_id** I added in the column.

**Comment by silentworks** [comment]
Please follow the instructions when creating an issue and provide steps to reproduce the issue. The steps you have provided doesn't result in what you describe, its better if you provide a repoducible example repo with the issue.

**Comment by akarshghale** [comment]
Man that's a lot of work and very less time.

```
Just create a table (Enable RLS) and add a user_id column.

Insert a record into that table with user_id column the same as the UID of the user registered. (Using service_role key)

Experience the blasphemy.

```
