### ISSUE TITLE
Client/Gateway sending requests as authenticated even when using service_role key

### ISSUE THREAD

**Issue by akarshghale** [supabase/supabase-py#1002]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm encountering a strange issue with my database when inserting or fetching records. It works perfectly on my localhost, but on the hosted staging server, it throws a bug. Records are being fetched and inserted as authenticated even when using service_role.

Details:

On localhost, I’m using version 2.0.6, while staging was on 2.10.0. Thinking it might be a version mismatch, I downgraded the staging server back to 2.0.6, but the issue persists.

The oddest part: the `user_id` value I’m inserting somehow becomes the authorized user in logs. For example, if I insert a record with `user_id` as `3023e35f-6d63-4587-8f4d-78a5112315d2`, the logs show this user as the one making the request—even though it should be the service_role.

This is log of one such instance:

```
  "host": "awvqtiwhrcfnxxxxxxxxx.supabase.co",
  "method": "POST",
  "path": "/rest/v1/unprocessed_reviews",
  "port": null,
  "protocol": "https:",
  "sb": [
    {
      "auth_user": "3023e35f-6d63-4587-8f4d-78a5112315d2",
      "jwt": [
        {
          "apikey": [
            {
              "invalid": null,
              "payload": [
                {
                  "algorithm": "HS256",
                  "issuer": "supabase",
                  "role": "service_role",
                  "signature_prefix": "Kexzvj",
                  "subject": null
                }
              ]
            }
          ],
          "authorization": [
            {
              "invalid": null,
              "payload": [
                {
                  "algorithm": "HS256",
                  "issuer": "https://awvqtiwhxxxxxxxxx.supabase.co/auth/v1",
                  "key_id": "gnKsQ+2zzxM9F1RT",
                  "role": "authenticated",
                  "signature_prefix": "6_lc4M",
                  "subject": "3023e35f-6d63-4587-8f4d-78a5112315d2"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
```

As can be seen above, the roles differ. 

I am guessing this can be an issue with the gateway as it seems to persist on both new and old client versions and weirdly happens on hosted ones.

## To Reproduce

When making an insert or fetch request on tables.

## Expected behavior

Should insert or fetch records as service_role without hitting RLS.

## System information

- OS: macOS latest
- Browser (if applies) NA
- Version of supabase-js: 2.0.6, 2.0.10
- Version of Node.js: NA

## Additional context

I feel the problem is on the gateway side as it seems to exists on different client versions.

**Comment by silentworks** [comment]
You are going to have to provide a repoducible example repo with this as I cannot replicate this and this has not been reported by anyone else so It's an isolated case and it's probably something in your code rather than an issue with the library.

**Comment by akarshghale** [comment]
I understand but it is literally the same code that everyone uses to fetch or insert.

Can you look at the logs I shared. Why are there 2 roles? instead of it just being service_role?

**Comment by silentworks** [comment]
I can provide you with further help when you provide a reproducible example repository. There is only ever two roles if you are sending both. I think Gary explained this in the Discord post you opened too. The logs doesn't tell much in the situation.

**Comment by akarshghale** [comment]
Issue was logic related. Apologies for this!
