### ISSUE TITLE
wrap postgrest-py

### ISSUE THREAD

**Issue by awalias** [supabase/supabase-py#2]
Use [postgrest-py](https://github.com/supabase/postgrest-py) and [supabase-js](https://github.com/supabase/supabase-js) as reference implementations

**Comment by prettyirrelevant** [comment]
I'd love to do this. Can i go ahead with the task

**Comment by lqmanh** [comment]
@prettyirrelevant Please go ahead.
I'm a bit busy with my work now but willing to review your PR or give you a hand if you need.

**Comment by gmarinella9** [comment]
> I'd love to do this. Can i go ahead with the task

tell me if you need help with something, I want to participate in this kind of projects

**Comment by prettyirrelevant** [comment]
@lqmanh alright then i'll start asap.

**Comment by prettyirrelevant** [comment]
#4 wrapped postgres-py
