### ISSUE TITLE
Enforce code consistency via pre-commit

### ISSUE THREAD

**Issue by olirice** [supabase/supabase-py#26]
# Feature request

Is there any interest in hooking up [pre-commit](https://pre-commit.com/) with the usual battery hooks for python libraries e.g. [black](https://github.com/psf/black), [isort](https://pycqa.github.io/isort/), [autoflake](https://github.com/myint/autoflake), and [mypy](https://github.com/python/mypy), to enforce code consistency/standards?

If so, I'm happy to open a PR

**Comment by J0** [comment]
Yeah! I personally  think that a pre-commit hook with `isort`, `black`  `autoflake` , and `mypy` would be really helpful. We should probably add a check in CI as well
