### ISSUE TITLE
Initializing python supabase client with timeout does not work as displayed on website. 

### ISSUE THREAD

**Issue by Simar-Kohli** [supabase/supabase-py#487]
**Describe the bug**

I'm trying to set a timeout on the client (since i've been getting httpx read timeout errors). 

```
import os
from supabase import create_client, Client

url: str = os.environ.get("SUPABASE_URL")
key: str = os.environ.get("SUPABASE_KEY")
supabase: Client = create_client(url, key, options={'timeout': 10})
```

This is as displayed on the website: https://supabase.com/docs/reference/python/initializing

**To Reproduce**
Put this code into a python file, and attempt to execute with current public pip3 install of supabase. 

**Expected behavior**
I expected it to be a valid client instance and start to use it for my python script. Instead, I get this error: 

Traceback (most recent call last):
  File "/Users/XXXXX/Desktop/XXXXXX/XXXXXX/deployableApprovals.py", line 27, in <module>
    supabaseClient: Client = create_client(SUPABASEURL, SUPABASEKEY, {'timeout': 10})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/supabase/client.py", line 248, in create_client
    return Client(supabase_url=supabase_url, supabase_key=supabase_key, options=options)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/supabase/client.py", line 61, in __init__
    options.headers.update(self._get_auth_headers())
AttributeError: 'dict' object has no attribute 'headers'

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by Simar-Kohli** [comment]
I figured a workaround: 
```
from supabase.lib.client_options import ClientOptions

clientOptions = ClientOptions(postgrest_client_timeout=999999)
supabaseClient: Client = create_client(SUPABASEURL, SUPABASEKEY, clientOptions)
```

Seems to solve the issue. Not sure if the website docs are out of date or maybe I'm still doing something wrong.

**Comment by Simar-Kohli** [comment]
Well while this works on my local machine, this does not run on an EC2 instance. Would love some assistance

**Comment by jtewright** [comment]
I experienced this problem too, and found that **in addition** to setting `postgrest_client_timeout` when initiating the python client, you have to change the default `statement_timeout` for the correct role through the Supabase dashboard SQL Editor, as per https://supabase.com/docs/guides/database/postgres/configuration#changing-the-default-timeout.

Oddly, while my python client uses the service_role API key, I needed to alter the `statement_timeout` for the `authenticated` role (note: not the `authenticator` role). Is that expected?

Note also that after 360s the request will error with the message: `The upstream server is timing out`.

**Comment by silentworks** [comment]
The docs has been updated on the website to show the correct way of doing timeouts. https://supabase.com/docs/reference/python/initializing
