### ISSUE TITLE
Support realtime subscription

### ISSUE THREAD

**Issue by NixBiks** [supabase/supabase-py#612]
Currently realtime subscription is not possible. For some reason the client is [commented out in the code](https://github.com/supabase-community/supabase-py/blob/f76ac69bb12d65e5321ec1753a97020e3583ed19/supabase/client.py#L78).

Are there any plans on adding it back in? Related to #20 - I have searched for answers why it's disabled but haven't seen any

**Comment by silentworks** [comment]
This will be added back in soon. We are still working on getting this updated, it's on our roadmap but is taking longer than expected. We should have a version with this in the next two weeks or so.

**Comment by NixBiks** [comment]
Cool. I built my own implementation using [websockets](https://websockets.readthedocs.io/en/stable/). My implementation is an async framework instead - let me know if I can help with your implementation.

**Comment by bitnom** [comment]
> This will be added back in soon. We are still working on getting this updated, it's on our roadmap but is taking longer than expected. We should have a version with this in the next two weeks or so.

what's the hold-up with it? I came up with a client for it relatively easily. Maybe it's not as complete as one would like for public consumption but pub/sub and presence are pretty straight-forward. Just need more contribs?

**Comment by bitnom** [comment]
Is it still worth submitting PRs to the realtime repo or are you planning to start over with it for integration here? I have private commits for the current realtime repo, as well as an implementation from scratch which I could refactor to conform to this codebase.

**Comment by SinaKarimi7** [comment]
> Is it still worth submitting PRs to the realtime repo or are you planning to start over with it for integration here? I have private commits for the current realtime repo, as well as an implementation from scratch which I could refactor to conform to this codebase.

Hi, I need the realtime feature of supabase in my project. Could it possible to share this part with me?

**Comment by bitnom** [comment]
> > Is it still worth submitting PRs to the realtime repo or are you planning to start over with it for integration here? I have private commits for the current realtime repo, as well as an implementation from scratch which I could refactor to conform to this codebase.
> 
> Hi, I need the realtime feature of supabase in my project. Could it possible to share this part with me?

did you already try [supabase-community/realtime-py ](https://github.com/supabase-community/realtime-py)? My recode isn't ready for public consumption but I'll make it public this week. I'm making it conform to the main supabase client for potential merger..

There's also [bitnom/aiorealtime](https://github.com/bitnom/aiorealtime), which was basically me encountering a race condition using multiple realtime-py instances in fastapi background tasks, and having an LLM do shoddy refactors to resolve it.

**Comment by SinaKarimi7** [comment]
> > > Is it still worth submitting PRs to the realtime repo or are you planning to start over with it for integration here? I have private commits for the current realtime repo, as well as an implementation from scratch which I could refactor to conform to this codebase.
> > 
> > 
> > Hi, I need the realtime feature of supabase in my project. Could it possible to share this part with me?
> 
> did you already try [supabase-community/realtime-py ](https://github.com/supabase-community/realtime-py)? My recode isn't ready for public consumption but I'll make it public this week. I'm making it conform to the main supabase client for potential merger..
> 
> There's also [bitnom/aiorealtime](https://github.com/bitnom/aiorealtime), which was basically me encountering a race condition using multiple realtime-py instances in fastapi background tasks, and having an LLM do shoddy refactors to resolve it.

Thank you for mentioning [supabase-community/realtime-py ](https://github.com/supabase-community/realtime-py). I hadn't noticed it before.

Also, It would be great if your work gets merged.

**Comment by silentworks** [comment]
This is now supported in the latest `2.7.2`, but note it only works in the `async` client.
