### ISSUE TITLE
Advice or example of mocking the client for tests

### ISSUE THREAD

**Issue by philliphartin** [supabase/supabase-py#681]
**Is your feature request related to a problem? Please describe.**
- I'm working on a FastAPI project that uses the `supabase-py` client. 
- I am writing tests focused on API interaction (payload validation, return structure, etc).
- Many of the endpoints interact with the supabase client to fetch data, perform some transforms and return it.
- I want to mock the client and fake a query return - without actually calling Supabase.
- However, I cannot find an example of best practice on how to do this.

**Describe the solution you'd like**
- An example of how to mock the client to provide mocked query returns.

**Describe alternatives you've considered**
- Considered running local DB to run tests against - but feels heavy

**Comment by Atticuszz** [comment]
[repo](https://github.com/Atticuszz/fastapi_supabase_template)
hey bro👋，there is base template of fastapi+ supabase with 90+% test
 coverage，although i do not apply mock client tests，hope the rest of tests or other code would help💪

**Comment by philliphartin** [comment]
Thank you @Atticuszz, I'll take a read and hope to understand it :)

**Comment by tinvaan** [comment]
@philliphartin have you tried https://vcrpy.readthedocs.io/en/latest ? 

Basically, you keep aside a test account and use it with the API once. vcr-py will cache the responses and reuse them subsequently. A workaround like this might be your best bet in the absence of a dynamic & stateful mocking library.

**Comment by philliphartin** [comment]
That's actually really cool @tinvaan. Certainly will save a lot of effort. Thanks

**Comment by syou98** [comment]
I use for it a special account for it. When running test, at the beggining my test load all my tables, functions, triggers, etc ... via psql command. Then it launch all my scenarios including business logic, and then when it finish, it drops all to clean it for the next test.
So for my real project, I just need to change api keys, variables (for psql) and loads all tables, functions, etc ...

@philliphartin I have a question. Do you use middleware for your project ?
Thank you

**Comment by silentworks** [comment]
Closing as there were a few suggestions given for this task.

**Comment by josiahcoad** [comment]
@tinvaan love VCR!!
