### ISSUE TITLE
Which version is most up-to-date?

### ISSUE THREAD

**Issue by karolzlot** [supabase/supabase-py#69]
**Describe the bug**
pip by default install now version 0.1.2. But newest version is 0.0.3.

https://pypi.org/project/supabase/#history

![image](https://user-images.githubusercontent.com/11590960/137605958-d7856785-71b6-43cf-9587-b084134d4b5e.png)

**To Reproduce**
1.  `pip install supabase`

**Expected behavior**
It should install latest version

**Screenshots**
Above

**Desktop (please complete the following information):**
n/a
**Smartphone (please complete the following information):**
n/a
**Additional context**
n/a

**Comment by J0** [comment]
Have deleted all outdated versions, should default to 0.0.3 now

**Comment by dreinon** [comment]
Awesome, issue solved then :)
