### ISSUE TITLE
Use tox for automating tests in different venvs

### ISSUE THREAD

**Issue by tinvaan** [supabase/supabase-py#696]
**Is your feature request related to a problem? Please describe.**
Tox project(https://tox.wiki) seems like a more useful addition to this project and can be used in place of `Makefiles` to invoke tests and other automations.

Tox also allows isolated builds against multiple virtual environments and is tailor-made for Python projects.

**Describe the solution you'd like**
We can drop the `Makefiles` in favour of `tox.ini` setup scripts. I have a sample PR opened at https://github.com/tinvaan/supabase-py/pull/1

What do we feel about this?

**Comment by silentworks** [comment]
This would be a shift in the workflow of what everyone on the project is used to and introducing a new config to new developers on this project will be harder than a Makefile which they might have been introduced to before. Makefiles are more universal and in my opinion easier to read and understand. This Tox configuration file takes a while to understand, also the benefit of the isolated Python env is already available in our CI. I'm going to reject this change for now as it will cause more friction than anything else.
