### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by Jacobsolawetz** [supabase/supabase-py#8]
# Bug report

## Describe the bug

Syntax bug on install:

```
Traceback (most recent call last):
  File "/Users/wolf/test/supabase-py/test.py", line 2, in <module>
    from supabase_py import create_client, Client
  File "/Users/wolf/test/supabase-py/supabase_py/__init__.py", line 2, in <module>
    from . import lib
  File "/Users/wolf/test/supabase-py/supabase_py/lib/__init__.py", line 2, in <module>
    from . import query_builder
  File "/Users/wolf/test/supabase-py/supabase_py/lib/query_builder.py", line 8, in <module>
    from .realtime_client import SupabaseRealtimeClient
  File "/Users/wolf/test/supabase-py/supabase_py/lib/realtime_client.py", line 21
    if (payload.type === 'UPDATE' or payload.type === 'DELETE'):                  ^
```

## To Reproduce

`clone` `python3 -m venv env` `source env/bin/activate` `clone` `pip install -e .` and run example code in README

```
import os
from supabase_py import create_client, Client

url: str = "URL"
key: str = "KEY"
supabase: Client = create_client(url, key)
```

## Expected behavior

A successful import and set up of client

## Additional context

These repo is awesome and would definitely streamline part of the application i'm building on Supabase - a python API would like to read from the database and perform some calcs - but I can't seem to stand it up. Tried all of the branches.

**Comment by Jacobsolawetz** [comment]
Fixing the syntax leads to this error `ModuleNotFoundError: No module named 'realtime_py'`. That's also the error you get if you try to install from master.

**Comment by fedden** [comment]
Hi @Jacobsolawetz thanks for the issue. We are actively developing on this and hope to have the client in a basic working order within a week or so - but don't hold me to that haha!

We have a few PRs that are getting merged soon so please keep an eye on things.

**Comment by Jacobsolawetz** [comment]
@fedden - epic, looking forward to it! Thank you for your work

**Comment by fedden** [comment]
Hey @Jacobsolawetz I've pushed the fix to my working branch - `feature/update-to-latest-gotrue-py`. 

Heads up - to use this branch there are a couple of dependancies you'd need to install manually to get things working, and we'll hopefully get things more streamlined soon after we get a few PRs merged but until then you'll need to install the following:
- https://github.com/supabase/realtime-py (not sure which branch - @J0 ?)
- my fork of https://github.com/fedden/gotrue-py

**Comment by Jacobsolawetz** [comment]
Awesome! sounds good, sounds good, I'll check it out - thanks again

**Comment by J0** [comment]
Hey @fedden and @Jacobsolawetz,

Thanks for your patience. The version of `realtime-py` listed is not up to date -- I have just updated it. Alternatively, as @fedden has mentioned you can install the `master` branch of the repository manually. 

I'm attempting to integrate the `realtime-py` library now and will let you know once it's ready.

Thanks for your understanding on this!

Joel

**Comment by fedden** [comment]
Update: I've pushed the latest gotrue to pypi - that should be working fine now, will hopefully get my branch merged to develop asap

**Comment by fedden** [comment]
merged!

**Comment by fedden** [comment]
Closing this, lmk if there is any issue.
