### ISSUE TITLE
Update gotrue to supabase-auth in pyproject.toml

### ISSUE THREAD

**Issue by mathatan** [supabase/supabase-py#843]
# Chore

## Describe the chore

[Pyproject.toml ](https://github.com/supabase-community/supabase-py/blob/main/pyproject.toml) is still pointing to the project name `gotrue` instead of `supabase-auth` making it impossible to replace the said package with a forked version.

## Additional context

I'm unable to use a fork for supabase-auth without also forking supabase-py which makes it impossible to side-step the issue mentioned in: https://github.com/supabase-community/auth-py/issues/537

**Comment by silentworks** [comment]
This will be a breaking change, so we will wait a bit before this happens.

**Comment by silentworks** [comment]
This will happen when version `3.0.0` is being worked on.
