### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by DackJempsey** [supabase/supabase-py#870]
# Bug report
In version 2.6.0 there is an import error
## Describe the bug

ImportError: cannot import name 'DEFAULT_FUNCTION_CLIENT_TIMEOUT' from 'supafunc.utils' (/usr/local/lib/python3.11/site-packages/supafunc/utils.py)
## To Reproduce
```
from supabase import create_client, Client
```
1. import create_client, Client
2. See error

## Expected behavior
Not to have an import error

## System information

- OS: Ubuntu 20

- Version of supabase: 2.6.0

**Comment by silentworks** [comment]
Delete your virtual env and install the dependencies again. You will only get the error if you don't have the latest `supafunc` installed.

**Comment by doevent** [comment]
It worked for me:

`pip install -U supafunc`

**Comment by Genius-Raptor** [comment]
Yes, it's probably an issue with pip. Import errors like these are incredibly common. Just clear your cache, reinstall supabase, cross your fingers and hope it works.

**Comment by Nikdedov** [comment]
Just updating the `supafunc ` worked for me

**Comment by silentworks** [comment]
Closing this out as it's not a package issue but more of a pip issue that can be resolved by updating the dependencies.
