### ISSUE TITLE
Error with RPC Calls and select queries with postgrest v0.16.9

### ISSUE THREAD

**Issue by 97k** [supabase/supabase-py#872]
# Bug report

## Describe the bug

This started arising with postgrest v0.16.9 only, it was working perfectly with version v0.16.8

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Make a database function with parameter
2. run it with supabase.rpc in v2.6
3. Nothing will be returned from the db, probably malformed parameter

## Expected behavior

It should work and proper response from db should be returned
## System information

- OS: docker
- Version of supabase-py: v2.5+

**Comment by silentworks** [comment]
Please show code example when opening issues to do with code bugs. I've tested this and cannot replicate the issue you are having. I've attached a video showing this working. I'm also using the latest 0.16.9 version of the `postgrest` library.

https://github.com/user-attachments/assets/fd149b53-dc4e-4bdc-a56d-241d9a18ac88

**Comment by 97k** [comment]
Thank you for checking it out.
I will check in with my container and share code example soon.

**Comment by silentworks** [comment]
Closing this out as there has been no reply from OP and I've shown this working in the video above.
