### ISSUE TITLE
should_create_user isn't working on otp sign in

### ISSUE THREAD

**Issue by hhubble** [supabase/supabase-py#882]
- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using the "should_create_user" option under the "sign_in_with_otp" method, it's not having an affect (it creates a user every time regardless). 

## To Reproduce

supabase.auth.sign_in_with_otp({
            "email": email,
            "options": {"should_create_user": False}
            })

## Expected behavior

When the flag is False, a new user should not be created.

## Screenshots

NA

## System information

Python library

## Additional context

NA

**Comment by silentworks** [comment]
I'm unable to replicate this. My guess is you are using an old version of the library, this has been fixed since version 2.5.3 of supabase_auth. https://github.com/supabase/auth-py/releases/tag/v2.5.3

**Comment by silentworks** [comment]
The flag can't take precedence over an admin privilege as this would render the admin privilege ineffective.
