### ISSUE TITLE
AsyncStorageClient.__init__() takes from 3 to 4 positional arguments but 5 were given

### ISSUE THREAD

**Issue by michaelchen01** [supabase/supabase-py#891]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Initializing the current storage client (either via a synchronous client or asynchronous client) results in this error
```AsyncStorageClient.__init__() takes from 3 to 4 positional arguments but 5 were given```

I am initializing it according to the docs, but lmk if that's not correct. The client itself is initialized as:
```
self.supabase = await supabase.acreate_client(
            settings.supabase.PROJECT_URL,
            settings.supabase.ANON_KEY
        )
```

FWIW, I also tried with the synchronous client, and am seeing the same behavior. I've also tried deleting my virtual env + clean install and it still repros. Currently trying to figure out which version works.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Initialize any supabase client
2. Try to access the storage client via `supabase.storage` at runtime.

## Expected behavior

The supabase storage client should be instantiated without throwing an error.

## Screenshots

More of the stack trace:
```
  File "<redacted>", line 359, in fetch_resource_content
    return await self.supabase.storage.from_(bucket).download(full_path)
                 ^^^^^^^^^^^^^^^^^^^^^
  File "<redacted>", line 183, in storage
    self._storage = self._init_storage_client(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<redacted>", line 242, in _init_storage_client
    return AsyncStorageClient(storage_url, headers, storage_client_timeout, verify)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: AsyncStorageClient.__init__() takes from 3 to 4 positional arguments but 5 were given
```

## System information

- Version of supabase-py: 2.6.0

**Comment by kowshik24** [comment]
Hi @michaelchen01 is there any parameter `DEFAULT_STORAGE_CLIENT_TIMEOUT` that you defined? While initializing the storage client?

**Comment by Nikdedov** [comment]
@michaelchen01 updating `storage3` manually helped me, because after updating `supabase`, it conflicts with older `storage3`. As I see:
1. Newer version of supabase try to initialise SyncStorageClient with 4 parameters:
`    def _init_storage_client(
        storage_url: str,
        headers: Dict[str, str],
        storage_client_timeout: int = DEFAULT_STORAGE_CLIENT_TIMEOUT,
        verify: bool = True,
    ) -> SyncStorageClient:
        return SyncStorageClient(storage_url, headers, storage_client_timeout, verify)`
2. When older version of storage3 accept only 3 parameters:
`    def __init__(
        self,
        url: str,
        headers: dict[str, str],
        timeout: int = DEFAULT_TIMEOUT,
    ) -> None:`
    
    JFYI, New 'verify' parameter was added [here](https://github.com/supabase/storage-py/commit/9ad75b0a7259dcd21c2a854ca4a498b67afa1611) on Jun 4, 2024

**Comment by kowshik24** [comment]
gotcha!

**Comment by silentworks** [comment]
Yes this would be due to dependency not being updated. Update your dependencies and this should work.
