### ISSUE TITLE
2.7.0 SupabaseRealtimeClient import missing

### ISSUE THREAD

**Issue by dpills** [supabase/supabase-py#895]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Running supabase 2.7.0 raises a `ModuleNotFoundError` due to not removing the SupabaseRealtimeClient import. 

## To Reproduce

Run a python script utilizing supabase 2.7.0.

## Bad Import

<https://github.com/supabase/supabase-py/blob/main/supabase/client.py#L19>
```python
# Lib
from .lib.client_options import ClientOptions
from .lib.realtime_client import SupabaseRealtimeClient
```

## Removed from `lib`
<https://github.com/supabase/supabase-py/blob/main/supabase/lib/__init__.py>

<https://github.com/supabase/supabase-py/commit/08496eb4c1c203d2806fc44753f3bddc4b463db0#diff-27f9014923633cc0c1a17e708523fcf210a925174ae73578db53383ce6f95cd9>

## System information

- OS: macOS Sonoma 14.5
 
## Traceback
```bash
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/user/projects/project/api/app/main.py", line 13, in <module>
    from app.routers.auth import auth
  File "/Users/user/projects/project/api/app/routers/auth/auth.py", line 11, in <module>
    from app.utilities.clients import get_supabase_public_client
  File "/Users/user/projects/project/api/app/utilities/clients.py", line 7, in <module>
    from supabase.client import ClientOptions
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/api-F9Sx80VA-py3.12/lib/python3.12/site-packages/supabase/client.py", line 19, in <module>
    from .lib.realtime_client import SupabaseRealtimeClient
ModuleNotFoundError: No module named 'supabase.lib.realtime_client'
````

**Comment by grdsdev** [comment]
Hi @dpills thanks, 

quick question, are you using `SupabaseRealtimeClient` somehow? Or is just facing issue with the wrong import from client lib?

**Comment by dpills** [comment]
@grdsdev Nope, I am not importing or using the realtime client in this application and it is throwing that error on startup. From the stack trace, it seems like this occurs when importing `ClientOptions` to instantiate the client. 

This is the config I am using.

```python
from supabase import create_client
from supabase.client import ClientOptions

from app.config import settings

supabase = create_client(
    settings.supabase_url,
    settings.supabase_key,
    options=ClientOptions(
        postgrest_client_timeout=10,
        storage_client_timeout=10,
        schema="public",
    ),
)
```

**Comment by grdsdev** [comment]
Got it, pushing a fix ASAP

**Comment by dpills** [comment]
@grdsdev Awesome, thanks for the quick fix and I really appreciate all the work on this Supabase client. 🙂
