### ISSUE TITLE
Realtime is not available when using sync client

### ISSUE THREAD

**Issue by Player-14** [supabase/supabase-py#909]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Realtime is not available when using the sync client in supabase-py.
The traceback is:
```
Traceback (most recent call last):
  File "C:\Users\USER\Desktop\Apps\ChatRock\chatrock\main.py", line 86, in <module>
    messages = supabase.channel("messages")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\Apps\ChatRock\venv\Lib\site-packages\supabase\_sync\client.py", line 204, in channel
    return self.realtime.channel(topic, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\Desktop\Apps\ChatRock\venv\Lib\site-packages\realtime\_sync\client.py", line 39, in channel
    raise NotImplementedError(NOT_IMPLEMENTED_MESSAGE)
NotImplementedError: This feature isn't available in the sync client. You can use the realtime feature in the async client only.
```
## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```
from supabase import create_client, Client

supabase: Client = create_client("SUPABASE_URL", "SUPABASE_KEY")
messages = supabase.channel("messages") # This triggers the error
```
1. Create supabase project with a realtime table called "messages"
2. Input URL and key
3. Run code in python

## Expected behavior

The module should just subscribe to the channel without tracebacks.

## System information

- OS: Windows 10
- Version of realtime-py: 2.0.2
- Version of supabase-py: 2.7.2
- Version of Python: 3.12.4

## Additional context

I am aware that realtime is available in the async class, but I prefer the sync class for ease of use.

**Comment by silentworks** [comment]
It's not a bug, its a feature. This won't be changed until we find a way to make websockets work without asyncio.

**Comment by sleeyax** [comment]
Where is the async python client even documented? I can't for the life of me find it.

**Comment by dhananjay1438** [comment]
Looks like there's one more change in the code provided above, as of today 21st Feb 2025, you can't use `await` with

```
(supabase.realtime
           .channel("my_channel")
           .on_postgres_changes("*", schema="public", table="my_table", callback=my_callback)
           .subscribe())
```

So the new code should be
```
supabase: AClient = await acreate_client(getenv("SUPABASE_URL"), getenv("SUPABASE_KEY"))

def my_callback(payload):
       print(payload)

await supabase.realtime.connect()

(supabase.realtime
     .channel("my_channel")
     .on_postgres_changes("*", schema="public", table="my_table", callback=my_callback)
     .subscribe())

await supabase.realtime.listen()
```

**Comment by techno-3282** [comment]
Is it working for you guys? Can someone add whole code here? i am not able to run await without async. Also if you can add what supabase version used here
