### ISSUE TITLE
Missing await on 'realtime.set_auth' for async client.

### ISSUE THREAD

**Issue by LuisLechugaRuiz** [supabase/supabase-py#919]
# Bug report

- [ - ] I confirm this is a bug with Supabase, not with my own application. 
- [ - ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Async client is broken due to a missing 'await' at [self.realtime.set_auth()](https://github.com/supabase/supabase-py/blob/main/supabase/_async/client.py#L301)

## To Reproduce

Initialize async client and propagate a Auth event.

## Expected behavior

Auth event triggers supabase real time which push the content over websocket asynchronously.

## Solution

- [supabase-auth](https://github.com/supabase/auth-py/pull/591)
- [supabase-py](https://github.com/supabase/supabase-py/pull/920)

**Comment by silentworks** [comment]
This is an issue that needs to be resolved but I don't think this is the approach to solving this. The realtime client should follow the other client libraries and take in a header property on initialization and that header should be updated each time an auth event happens.
