### ISSUE TITLE
Unable to pass arguments (i.e. auto_reconnect) to AsyncRealtimeClient

### ISSUE THREAD

**Issue by yorickvanzweeden** [supabase/supabase-py#927]
# Issue
I seem to be unable to pass arguments, such as `auto_reconnect` to the `AsyncRealtimeClient`. Therefore, I need to patch the client after initialization.

```python
    client = await acreate_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_ROLE_SECRET)
    client.realtime = AsyncRealtimeClient(client.realtime_url, token=client.supabase_key, auto_reconnect=True)
    return client
```

## The problem
The `acreate_client` accepts `ClientOptions`, which has a `realtime` field with type `Optional[Dict[str, Any]]`. These will be passed to `_init_realtime_client`.

https://github.com/supabase/supabase-py/blob/bf252a2d5aff40444970e94b163c74344f50378c/supabase/_async/client.py#L84-L88

https://github.com/supabase/supabase-py/blob/bf252a2d5aff40444970e94b163c74344f50378c/supabase/_async/client.py#L218-L225

However, the options are passed to params, and I cannot pass the auto_reconnect flag (or other attributes) via the supabase module.

[permalink](https://github.com/supabase/realtime-py/blob/d414762bdd48d21fcac7f42484e151b9db50a84f/realtime/_async/client.py#L37-L47)
```python
class AsyncRealtimeClient:
    def __init__(
        self,
        url: str,
        token: str,
        auto_reconnect: bool = False,
        params: Dict[str, Any] = {},
        hb_interval: int = 30,
        max_retries: int = 5,
        initial_backoff: float = 1.0,
    ) -> None:
```

## Suggestion
```python
@staticmethod
def _init_realtime_client(
    realtime_url: str, supabase_key: str, options: Optional[Dict[str, Any]] = None
) -> AsyncRealtimeClient:
    """Private method for creating an instance of the realtime-py client."""
    if options is None:
        options = {}
    return AsyncRealtimeClient(
        realtime_url, token=supabase_key, **options
    )
```

Unpack `options` immediately. This would allow configuration such as:
```python
    options = ClientOptions(
        realtime={
            "auto_reconnect": True,
        }
    )
    client = await acreate_client(settings.SUPABASE_URL, settings.SUPABASE_SERVICE_ROLE_SECRET, options)
```

**Comment by krishpy99** [comment]
Hi is there a way I can test this locally after I fix this? I am new to supabase and open source.. I have used supabase as a client but I am unsure of the use-case as a realtime client and how I should test the same.

**Comment by yorickvanzweeden** [comment]
> Hi is there a way I can test this locally after I fix this? I am new to supabase and open source.. I have used supabase as a client but I am unsure of the use-case as a realtime client and how I should test the same.

Not predictably, you need to wait hours until it randomly disconnects, and it might just keep silent. So you need to trigger it via database changes or realtime messages to verify the disconnect
