### ISSUE TITLE
Failing to sign-up

### ISSUE THREAD

**Issue by thierrymoudiki** [supabase/supabase-py#955]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

`{"detail":"Email address \"firstname.lastname@pm.me\" cannot be used as it is not authorized"}`

## To Reproduce

Try to sign-up to https://www.techtonique.net/

Logging-in works as it used to. Signing-up has been working until today. 

When inspecting the back-end, I'm able to see that the error precisely comes from the instruction: `response = supabase.auth.sign_up({"email": email, "password": password})`:

`INFO:     127.0.0.1:xxxx - "POST /signup HTTP/1.1" 400 Bad Request`

## Expected behavior

Successful sign-up. Status 200 OK. 

## Screenshots

<img width="713" alt="Capture d’écran 2024-10-06 à 21 10 59" src="https://github.com/user-attachments/assets/9326ec4a-29c3-45ce-9d5e-1737d516f569">

## System information

- Browser (if applies) [e.g. chrome, safari]
- Last version of supabase, always (should I change this and fix the version instead?)

**Comment by silentworks** [comment]
This is not related to the library, this was an infrastructure change. You should check this Supabase changelogs on GitHub discussions to learn more https://github.com/orgs/supabase/discussions/29370

**Comment by thierrymoudiki** [comment]
More precisely (for those who may read this while searching for help), it's related to a change in the infrastructure, that impacts the library, hence deprecating `supabase.auth.sign_up` (which is part of the library). Very short notice. Thanks for the link!

**Comment by silentworks** [comment]
@thierrymoudiki the infrastructure change doesn't deprecate any methods in this library.

**Comment by thierrymoudiki** [comment]
The fact is: the behavior of the function has changed. Short notice. Let's agree to disagree. Enough notifications.
