### ISSUE TITLE
Refactoring: TypedDict has been added to the typing module

### ISSUE THREAD

**Issue by newwingbird** [supabase/supabase-py#964]
# Chore

## Refactoring

In Python 3.8 and later, TypedDict has been added to the typing module.

https://github.com/supabase/supabase-py/blob/e9feb487f017c1d1aa0bbd0583c25016be9ad470/supabase/types.py#L1-L8

The README says `Install the package (for Python > 3.7):`, but I think it actually supports Python >= 3.9.

https://github.com/supabase/supabase-py/blob/e9feb487f017c1d1aa0bbd0583c25016be9ad470/README.md?plain=1#L39

https://github.com/supabase/supabase-py/blob/e9feb487f017c1d1aa0bbd0583c25016be9ad470/.github/workflows/ci.yml#L21

## Proposal
 It can be refactored as follows

```py
from typing import TypedDict

class RealtimeClientOptions(TypedDict, total=False):
    auto_reconnect: bool
    hb_interval: int
    max_retries: int
    initial_backoff: float
```

Here, instead of specifying each field as NotRequired, all fields are treated as optional with total=False. This makes the code simpler and more readable. [reference](https://docs.python.org/3/library/typing.html#typing.TypedDict)

If it's convenient for you, I would be happy to help you.

**Comment by silentworks** [comment]
Ah good catch. Also thanks for the PR, I will review it soon.
