### ISSUE TITLE
Unable to perform string concatenation with .select

### ISSUE THREAD

**Issue by rdong8** [supabase/supabase-py#973]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Trying to concatenate strings in a SELECT query just returns * instead.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a table
```sql
CREATE TABLE IF NOT EXISTS "test"(
  "json" JSONB NOT NULL
);
```
2. Insert using the Python client
```python
response = await (
    client
    .from_("test")
    .upsert({"json": {"hex": "abc123"}})
    .execute()
)
```
3. Try to select the inserted data using a concatenation
```python
response = await (
    client
    .from_("test")
    .select(r"'0x' || (json->>hex) AS hex")
    .execute()
)

print(response.data)
```

4. Output is equivalent to `SELECT *`
```python
[{'json': {'hex': 'abc123'}}]
```

## Expected behavior

I expected it to be equivalent to the following query:

```sql
SELECT '0x' || (json->>'hex') AS hex
FROM test;
```

Which would return:

| hex      |
| -------- |
| 0xabc123 |

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by silentworks** [comment]
This is not a bug as the sdk doesn't work this way. The API is based on postgrest and the syntax you have above is not a valid postgrest syntax.
