### ISSUE TITLE
Filtering through foreign table doesn't respect join hint syntax

### ISSUE THREAD

**Issue by notjustinshaw** [supabase/supabase-py#983]
I have a query in supabase-js that works, and when I translate it to supabase-py it doesn't work. I am on the latest version of each. From what I could gather while poking around, the python version doesn't seem to respect the join-hint PostgREST syntax for referencing tables with foreign keys.

### Javascript
```js
supabase
  .schema('pfr')
  .from('games')
  .select(`id,
    date,
    away_score,
    home_score,
    away_team:team_seasons!fk_away_team_id!inner(city, name),
    home_team:team_seasons!fk_home_team_id!inner(city, name),
  `)
  .ilike('away_team.name', awayTeam)
  .ilike('home_team.name', homeTeam);
```

### Python
```py
supabase
  .schema('pfr')
  .table('games')
  .select('''id,
    date,
    away_score,
    home_score,
    away_team:team_seasons!fk_away_team_id!inner(city, name),
    home_team:team_seasons!fk_home_team_id!inner(city, name),
  ''')
  .ilike('away_team.name', awayTeam)
  .ilike('home_team.name', homeTeam);
```

## Schema
The schema is what you would expect; a games table with two foreign keys each pointing at a team_season.

# Error Message
In PostgREST, you are supposed to be able to reference aliased foreign keys like this. It shouldn't assume the column is a column on the games table. Instead it should use the join-hint to compute a path to that table based on the constraints/keys available between the games table and team_seasons table (in this case, there are two paths: fk_home_team_id and fk_away_team_id).
```
APIError: {'code': '42703', 'details': None, 'hint': None, 'message': 'column games.away_team.name does not exist'}
```

**Comment by teodos** [comment]
getting what may be a very similar issue

say I'm trying
```
query = supabase.table('applicants').select(
            '*, profiles(id, name, email)'
)

or_conditions = []  
or_conditions.append(f"profiles.name.ilike.%{keyword}%")
or_conditions.append(f"profiles.email.ilike.%{keyword}%")
query = query.or_(', '.join(or_conditions)
```

I'm getting
```{'code': 'PGRST100', 'details': 'unexpected "a" expecting "not" or operator (eq, gt, ...)', 'hint': None, 'message': '"failed to parse logic tree ((profiles.name.ilike.%.me%,profiles.email.ilike.%.me%))```
which makes sense that .name' is not an operator
then I've tried doing `profiles->name` and `profiles->email`, and in that case, I'm getting

```{'code': '42703', 'details': None, 'hint': 'Perhaps you meant to reference the column "applications.profile_id".', 'message': 'column applications.profiles does not exist'}```

**Comment by silentworks** [comment]
@teodos this is not related and you should also provide your table details when posting. Your error is making reference to `applications` but your table is called `applicants`. Without seeing the tables we don't know what issue you could be having. Also open a separate issue with all the details I mentioned in this post.

**Comment by teodos** [comment]
Can't you just figure out the table structure from the post? (which btw it's not what this issue is about)

It's not about the structure or naming, but the join syntax that's not working (as the issue title suggests).

One thing you are right about is the table name (it's applications, not applicants)

Tables:
```
applications:
- id
- profile_id (fk profiles.id)

profiles:
- id
- name
- email
```

So again, same question with corrected table name:


I'm doing:
`keyword=".me"`

```
query = supabase.table('applications').select(
            '*, profiles(id, name, email)'
)

or_conditions = []  
or_conditions.append(f"profiles.name.ilike.%{keyword}%")
or_conditions.append(f"profiles.email.ilike.%{keyword}%")
query = query.or_(', '.join(or_conditions)
```

I'm getting
`{'code': 'PGRST100', 'details': 'unexpected "a" expecting "not" or operator (eq, gt, ...)', 'hint': None, 'message': '"failed to parse logic tree ((profiles.name.ilike.%.me%,profiles.email.ilike.%.me%))`
which makes sense that .name' is not an operator
then I've tried doing profiles->name and profiles->email, and in that case, I'm getting

`{'code': '42703', 'details': None, 'hint': 'Perhaps you meant to reference the column "applications.profile_id".', 'message': 'column applications.profiles does not exist'}`

**Comment by silentworks** [comment]
@teodos the docs clearly states how the `.or_` operator works and you aren't following it's syntax. As I've mentioned before your issue is not related to the OPs issue, you should open your own issue and stop adding to this one.

**Comment by notjustinshaw** [comment]
I’ll see if I can find time to set up an example.

The simplest case I can think of is the messages example from the js docs with a users table and a message table that references users twice, once for sender and once for recipient.

**Comment by silentworks** [comment]
@notjustinshaw I tested the message example from the docs and didn't get any issue with it.

**Comment by silentworks** [comment]
Here is a screen recording of me testing the sample data you mentioned in the docs with the Python client.

Turn your volume down as I might be a bit loud when talking in the video.

https://github.com/user-attachments/assets/560444ca-a607-474f-a1b8-e2ad95c5caa3

**Comment by silentworks** [comment]
No reply from OP from over a month now. Closing this out.

**Comment by notjustinshaw** [comment]
it’s still broken, I just haven’t had time to contribute the fix.

**Comment by notjustinshaw** [comment]
Perhaps now that this is an officially supported package from the Supabase team, someone could take a look to make sure clients are compatible with one another?
